version: "3.2"

volumes:
  jupyter-home:

services:
  spark-master:
    build: master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - type: bind
        source: ./data
        target: /spark/data
  spark-worker-1:
    build: worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - type: bind
        source: ./data
        target: /spark/data
  spark-worker-2:
    build: worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - type: bind
        source: ./data
        target: /spark/data
  spark-jupyter:
    build: jupyter
    container_name: spark-jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_EXECUTOR_MEMORY=1g"
      - "PYSPARK_DRIVER_MEMORY=1g"
      - "PYSPARK_DATA=/spark/data"
    volumes:
      - type: bind
        source: ./data
        target: /spark/data
      - jupyter-home:/home/jupyter
