version: "3.2"

services:
  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  jupyter:
    build: jupyter
    container_name: spark-jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "PYSPARK_EXECUTOR_MEMORY=5g"
      - "PYSPARK_DRIVER_MEMORY=5g"
      - "PYSPARK_DATA=/spark/data"
    volumes:
      - type: bind
        source: ./data
        target: /spark/data
